;  ASM code generated by mikroVirtualMachine for PIC - V. 5.0.0.2
;  Date/Time: 6/20/2006 10:35:06 PM
;  Info: http://www.mikroelektronika.co.yu


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;lites_test.c,1 :: 		void main() {
;lites_test.c,2 :: 		PORTA = 0;
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
$0006	$0185			CLRF	PORTA, 1
;lites_test.c,3 :: 		TRISA = 0;
$0007	$1683			BSF	STATUS, RP0
$0008	$0185			CLRF	TRISA, 1
;lites_test.c,5 :: 		while(1) {
$0009	$	L_main_0:
;lites_test.c,6 :: 		PORTA =  ~PORTA;
$0009	$1283			BCF	STATUS, RP0
$000A	$0985			COMF	PORTA, F
;lites_test.c,7 :: 		Delay_ms(1000);
$000B	$3006			MOVLW	6
$000C	$00FC			MOVWF	STACK_12
$000D	$30FF			MOVLW	255
$000E	$00FB			MOVWF	STACK_11
$000F	$30FF			MOVLW	255
$0010	$00FA			MOVWF	STACK_10
$0011	$0BFC			DECFSZ	STACK_12, F
$0012	$2814			GOTO	$+2
$0013	$281B			GOTO	$+8
$0014	$0BFB			DECFSZ	STACK_11, F
$0015	$2817			GOTO	$+2
$0016	$281A			GOTO	$+4
$0017	$0BFA			DECFSZ	STACK_10, F
$0018	$2817			GOTO	$-1
$0019	$2814			GOTO	$-5
$001A	$2811			GOTO	$-9
$001B	$301A			MOVLW	26
$001C	$00FB			MOVWF	STACK_11
$001D	$30FF			MOVLW	255
$001E	$00FA			MOVWF	STACK_10
$001F	$0BFB			DECFSZ	STACK_11, F
$0020	$2822			GOTO	$+2
$0021	$2825			GOTO	$+4
$0022	$0BFA			DECFSZ	STACK_10, F
$0023	$2822			GOTO	$-1
$0024	$281F			GOTO	$-5
$0025	$3042			MOVLW	66
$0026	$00FA			MOVWF	STACK_10
$0027	$0BFA			DECFSZ	STACK_10, F
$0028	$2827			GOTO	$-1
;lites_test.c,8 :: 		}
$0029	$2809			GOTO	L_main_0
;lites_test.c,9 :: 		}
$002A	$282A			GOTO	$
